config/routes.rb
Rails.application.routes.draw do
  resources :debtors
  root 'products#index'
  resources :products do
    get :autocomplete_product_name, :on => :collection
  end

  get 'product/:id/reload' => 'products#reload', as: :reload
  post 'product/:id/sell' => 'products#sell', as: :sell
  post 'day/close' => 'products#close_day', as: :close_day
  post 'debtor/update/debt' => 'debtors#add_bebt', as: :add_bebt
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_report.rb
class DailyReport < ApplicationRecord
end

app/models/debtor.rb
class Debtor < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/debtors_controller.rb
class DebtorsController < ApplicationController
  before_action :set_debtor, only: [:show, :edit, :update, :destroy]

  # GET /debtors
  # GET /debtors.json
  def index
    @debtors = Debtor.all
  end

  # GET /debtors/1
  # GET /debtors/1.json
  def show
  end

  # GET /debtors/new
  def new
    @debtor = Debtor.new
  end

  # GET /debtors/1/edit
  def edit
  end

  # POST /debtors
  # POST /debtors.json
  def create
    @debtor = Debtor.new(debtor_params)

    respond_to do |format|
      if @debtor.save
        format.html { redirect_to debtors_path, notice: 'Debtor was successfully created.' }
        format.json { render :show, status: :created, location: @debtor }
      else
        format.html { render :new }
        format.json { render json: @debtor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debtors/1
  # PATCH/PUT /debtors/1.json
  def update
    respond_to do |format|
      if @debtor.update(debtor_params)
        format.html { redirect_to debtors_url, notice: 'Debtor was successfully updated.' }
        # format.json { render :show, status: :ok, location: @debtor }
      else
        format.html { render :edit }
        format.json { render json: @debtor.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_bebt
    @debtor.update(debt: @debtor.debt + params[:debt])
    redirect_to debtor_path(@debtor)
  end

  # DELETE /debtors/1
  # DELETE /debtors/1.json
  def destroy
    @debtor.destroy
    respond_to do |format|
      format.html { redirect_to debtors_url, notice: 'Debtor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debtor
      @debtor = Debtor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def debtor_params
      params.require(:debtor).permit(:f_name, :l_name, :debt, :items)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :reload, :sell]
  autocomplete :product, :name,  :full => true


  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @reports = DailyReport.all
    @total_sales = DailyReport.where(updated_at: Time.zone.now.beginning_of_month..Time.zone.now.end_of_month).sum(:total_sales) + @products.where(updated_at: Time.zone.now.beginning_of_month..Time.zone.now.end_of_month).sum(:total_sales)
    @day_sales = @products.sum(:total_sales)
    @day_margins = @products.sum(:total_margin)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    # respond_to do |format|
      if @product.update(product_params)
        reload
        # format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        # format.json { render :show, status: :ok, location: @product }
      # else
      #   format.html { render :edit }
      #   format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    # end
  end

  def reload
    total_stock = @product.opening_stock + @product.purchases
    total_buying_cost = @product.buying_cost * @product.purchases
    margin = @product.selling_cost - @product.buying_cost
    total_margin = @product.total_sold * margin
    total_sales = @product.selling_cost * @product.total_sold
    closing_stock = @product.total_stock - @product.total_sold

    @product.update(total_stock: total_stock, total_buying_cost: total_buying_cost, margin: margin, total_margin: total_margin, total_sales: total_sales, closing_stock: closing_stock)
    redirect_to root_url
  end

  def sell
    closing_stock = @product.closing_stock - params[:quantity].to_i
    total_sold = @product.total_sold + params[:quantity].to_i
    total_margin = total_sold * @product.margin
    total_sales = total_sold * @product.selling_cost
    @product.update(closing_stock: closing_stock, total_sold: total_sold, total_margin: total_margin, total_sales: total_sales)
    reload
  end

  def close_day
    # Create gen report
    DailyReport.create!(report_params)
    # Save items with closong stock, total sales ets and export to pdf or excel
    Product.all.each do |prod|
      prod.update(opening_stock: prod.closing_stock, purchases: 0, total_stock: prod.closing_stock, total_sold: 0, total_margin: 0, total_sales: 0, closing_stock: 0)
    end
    redirect_to root_url
  end

  def open_day
    # assign closing stock to opening stock and reset purchases etc
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :opening_stock, :purchases, :total_stock, :total_sold, :buying_cost, :total_buying_cost, :selling_cost, :margin, :total_margin, :total_sales, :closing_stock)
    end

    def sell_params
      params.permit(:quantity)
    end

    def report_params
      params.permit(:report_date, :total_sales, :day_sales, :day_margin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  

end

app/helpers/debtors_helper.rb
module DebtorsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/debtors/_form.html.erb
<%= form_with(model: debtor, local: true) do |form| %>
  <% if debtor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(debtor.errors.count, "error") %> prohibited this debtor from being saved:</h2>

      <ul>
      <% debtor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :f_name %>
    <%= form.text_field :f_name %>
  </div>

  <div class="field">
    <%= form.label :l_name %>
    <%= form.text_field :l_name %>
  </div>

  <div class="field">
    <%= form.label :debt %>
    <%= form.text_field :debt %>
  </div>

  <div class="field">
    <%= form.label :items %>
    <%= form.text_field :items %>
  </div>

  <div class="actions">
    <%= form.submit 'Update', class: 'btn blue lighten-3' %>
  </div>
<% end %>

app/views/debtors/edit.html.erb
<h1>Editing Debtor</h1>

<%= render 'form', debtor: @debtor %>

<%= link_to 'Back', debtors_path, class: 'btn-large blue lighten-3' %>

app/views/debtors/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Shop', root_url, class: 'btn-large blue lighten-3' %>
<h1>Debtors</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Items</th>
      <th>Debt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @debtors.each do |debtor| %>
      <tr>
        <td><%= debtor.f_name %></td>
        <td><%= debtor.l_name %></td>
        <td><%= debtor.items %></td>
        <td><%= debtor.debt %></td>
        <td><%= link_to 'Update', edit_debtor_path(debtor), class: 'btn blue lighten-3' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Debtor', new_debtor_path, class: 'btn blue lighten-3v' %>

app/views/debtors/new.html.erb
<h1>New Debtor</h1>

<%= render 'form', debtor: @debtor %>

<%= link_to 'Back', debtors_path %>

app/views/debtors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>F name:</strong>
  <%= @debtor.f_name %>
</p>

<p>
  <strong>L name:</strong>
  <%= @debtor.l_name %>
</p>

<p>
  <strong>Debt:</strong>
  <%= @debtor.debt %>
</p>

<%= link_to 'Edit', edit_debtor_path(@debtor) %> |
<%= link_to 'Back', debtors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JustdrinksReporting</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :opening_stock %>
    <%= form.text_field :opening_stock %>
  </div>

  <div class="field">
    <%= form.label :purchases %>
    <%= form.text_field :purchases %>
  </div>

  <div class="field">
    <%= form.label :total_stock %>
    <%= form.text_field :total_stock %>
  </div>

  <div class="field">
    <%= form.label :total_sold %>
    <%= form.text_field :total_sold %>
  </div>

  <div class="field">
    <%= form.label :buying_cost %>
    <%= form.text_field :buying_cost %>
  </div>

  <div class="field">
    <%= form.label :total_buying_cost %>
    <%= form.text_field :total_buying_cost %>
  </div>

  <div class="field">
    <%= form.label :selling_cost %>
    <%= form.text_field :selling_cost %>
  </div>

  <div class="field">
    <%= form.label :margin %>
    <%= form.text_field :margin %>
  </div>

  <div class="field">
    <%= form.label :total_margin %>
    <%= form.text_field :total_margin %>
  </div>

  <div class="field">
    <%= form.label :total_sales %>
    <%= form.text_field :total_sales %>
  </div>

  <div class="field">
    <%= form.label :closing_stock %>
    <%= form.text_field :closing_stock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>


<div class="dashboard">
  <div class="row">
    <div class="card col s4 green">
      <h3>Month Sales</h3>
      <%= number_to_currency(@total_sales, :unit => "KES ") %>
    </div>
    <div class="card col s4 blue">
      <h3>Today's Sales</h3>
      <%= number_to_currency(@day_sales, :unit => "KES ") %>
    </div>
    <div class="card col s4 purple">
      <h3>Day's Margin</h3>
      <%= number_to_currency(@day_margins, :unit => "KES ") %>
    </div>
  </div>
</div>

<%= form_tag close_day_path do %>
  <%= date_field_tag :report_date, Date.today %>
  <%= hidden_field_tag :total_sales, @total_sales %>
  <%= hidden_field_tag :day_sales,  @day_sales %>
  <%= hidden_field_tag :day_margin, @day_margins %>
  <%= submit_tag 'Close Day', class: 'btn red lighten-3' %>
<% end %>
<%= link_to 'Debtors', debtors_path, class: 'btn-large blue lighten-3', style: 'float: right' %>

    <div id="present">
      <h1>Today</h1>
      <button class="btn-large blue lighten-3" style="float: right" onclick="history()">History</button>
      <table class="striped">
        <thead>
          <tr>
            <th>Item</th>
            <th>Opening stock</th>
            <th>Purchases</th>
            <th>Total stock</th>
            <th>Total sold</th>
            <th>Buying cost</th>
            <th>Total buying cost</th>
            <th>Selling cost</th>
            <th>Margin</th>
            <th>Total margin</th>
            <th>Total sales</th>
            <th>Closing stock</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @products.each do |product| %>
          <!-- Modal Structure -->
          <div id="modal<%= product.id %>" class="modal">
            <div class="modal-content">
              <h4><%= product.name %></h4>
              <p><%= number_to_currency(product.selling_cost, :unit => "KES ") %></p>
              <p>In Stock: <%= product.closing_stock %></p>
              <div class="form">
                <%= form_tag sell_path(product) do %>
                  <div class="field">
                    <%= number_field_tag :quantity, nil, :placeholder => "Enter Quantity" %>
                  </div>
                  <div class="field">
                    <%= submit_tag 'Post', class: 'btn blue lighten-3' %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="modal-footer">
              <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
            </div>
          </div>

            <tr>
              <td><%= product.name %></td>
              <td><%= product.opening_stock %></td>
              <td><%= product.purchases %></td>
              <td><%= product.total_stock %></td>
              <td><%= product.total_sold %></td>
              <td><%= number_to_currency(product.buying_cost, :unit => "KES ") %></td>
              <td><%= number_to_currency(product.total_buying_cost, :unit => "KES ") %></td>
              <td><%= number_to_currency(product.selling_cost, :unit => "KES ") %></td>
              <td><%= number_to_currency(product.margin, :unit => "KES ") %></td>
              <td><%= number_to_currency(product.total_margin, :unit => "KES ") %></td>
              <td><%= number_to_currency(product.total_sales, :unit => "KES ") %></td>
              <td><%= product.closing_stock %></td>
              <td> <button class="btn blue lighten-3" onclick="sell(<%= product.id %>)">Sell</button> </td>
              <td><%= link_to 'Reload', reload_path(product), class: 'btn green lighten-3' %></td>
              <td><%= link_to 'edit', edit_product_path(product), class: 'btn lighten-3' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div id="history" style="display: none">
      <h1>History</h1>
      <button class="btn-large blue lighten-3" style="float: right" onclick="present()"><%= Date.today.strftime("%A") %></button>
      <table class="striped">
        <thead>
          <th>Date</th>
          <th>Gross Sales</th>
          <th>Day Sales</th>
          <th>Day Margin</th>
        </thead>
        <tbody>
          <% @reports.each do |report| %>
            <tr>
              <td><%= report.report_date.strftime("%A") %>: <%= report.report_date %></td>
              <td><%= report.total_sales %></td>
              <% if report.id > 1 %>
                <% if report.day_sales > @reports.find(report.id - 1).day_sales %>
                  <td><%= report.day_sales %><i class="material-icons icon-green">arrow_drop_up</i></td>
                <% else %>
                  <td><%= report.day_sales %><i class="material-icons icon-red">arrow_drop_down</i></td>
                <% end %>
              <% else %>
                <td><%= report.day_sales %></td>
              <% end %>
              <% if report.id > 1 %>
                <% if report.day_margin > @reports.find(report.id - 1).day_margin %>
                  <td><%= report.day_margin %><i class="material-icons icon-green">arrow_drop_up</i></td>
                <% else %>
                  <td><%= report.day_margin %><i class="material-icons icon-red">arrow_drop_down</i></td>
                <% end %>
              <% else %>
                <td><%= report.day_margin %></td>
              <% end %>



            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <br>

<%= link_to 'Add Product', new_product_path, class: 'btn green lighten-3' %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Opening stock:</strong>
  <%= @product.opening_stock %>
</p>

<p>
  <strong>Purchases:</strong>
  <%= @product.purchases %>
</p>

<p>
  <strong>Total stock:</strong>
  <%= @product.total_stock %>
</p>

<p>
  <strong>Total sold:</strong>
  <%= @product.total_sold %>
</p>

<p>
  <strong>Buying cost:</strong>
  <%= @product.buying_cost %>
</p>

<p>
  <strong>Total buying cost:</strong>
  <%= @product.total_buying_cost %>
</p>

<p>
  <strong>Selling cost:</strong>
  <%= @product.selling_cost %>
</p>

<p>
  <strong>Margin:</strong>
  <%= @product.margin %>
</p>

<p>
  <strong>Total margin:</strong>
  <%= @product.total_margin %>
</p>

<p>
  <strong>Total sales:</strong>
  <%= @product.total_sales %>
</p>

<p>
  <strong>Closing stock:</strong>
  <%= @product.closing_stock %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>